# WARNING: This is an alpha spec of NSCL 2.0!!

host * {
    directory:./html
    apimode:0
    block-ua:match("Discordbot")
}

globals {
    http:1
    https:1
    port:8080
    https-port:8443
    key:./key.pem
    cert./cert.pem
}
