# WARNING: This is an alpha spec of NSCL 2.0!!

host 192.168.2.196 {
    directory:/home/nova/Downloads/test/html
    allowed-methods:GET
    block-ua:match("Discordbot"),match("Google")
}

host localhost {
    directory:/home/nova/PyWebServer/html2
    allowed-methods:GET,PUT
    block-ip:10.1.100.2
    block-ua:match("Discordbot")
}

host 192.168.1.213 {
    directory:/home/nova/PyWebServer/html
    allowed-methods:GET,PUT
    block-ip:10.1.100.2
    block-ua:match("Discordbot")
}

globals {
    http:1
    https:1
    port:8080
    https-port:8443
    allow-localhost:1
    key:/home/nova/PyWebServer/ssl/key.pem
    cert:/home/nova/PyWebServer/ssl/cert.pem
}
